version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: dummy
      runas: root
      content: |
        #!/bin/bash
        sudo rm -f /var/www/html/index.html

